//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Vaishnavi\SpotsyncFiles\01_SpotLocationVerification\bin\x64\Debug\SpotLocationVerification.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: Owner
//              Version: NX 2306
//              Date: 01-29-2026  (Format: mm-dd-yyyy)
//              Time: 16:07 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;
using System.IO;
using System.Collections.Generic;
using OfficeOpenXml;
using System.Linq;


//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class SpotLocationVerification
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group;// Block type: Group
    private NXOpen.BlockStyler.FileSelection nativeFileBrowser0;// Block type: NativeFileBrowser
    private NXOpen.BlockStyler.FileSelection nativeFileBrowser01;// Block type: NativeFileBrowser
    private NXOpen.BlockStyler.Group group1;// Block type: Group
    private NXOpen.BlockStyler.DoubleBlock double0;// Block type: Double
    private NXOpen.BlockStyler.Enumeration enum0;// Block type: Enumeration
    private NXOpen.BlockStyler.Button reportButton;// Block type: Button
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public SpotLocationVerification()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "SpotLocationVerification.dlx";
            theDialog = theUI.CreateDialog(System.IO.Path.Combine(AppContext.BaseDirectory, theDlxFileName));
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static int Main(string[] args)

    {
        SpotLocationVerification theSpotLocationVerification = null;
        try
        {
            theSpotLocationVerification = new SpotLocationVerification();
            // The following method shows the dialog immediately
            theSpotLocationVerification.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theSpotLocationVerification != null)
                theSpotLocationVerification.Dispose();
                theSpotLocationVerification = null;
        }
        return 0;
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
            GetUnloadOption(arg);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
            nativeFileBrowser0 = (NXOpen.BlockStyler.FileSelection)theDialog.TopBlock.FindBlock("nativeFileBrowser0");
            nativeFileBrowser01 = (NXOpen.BlockStyler.FileSelection)theDialog.TopBlock.FindBlock("nativeFileBrowser01");
            group1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group1");
            double0 = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double0");
            enum0 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum0");
            reportButton = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("reportButton");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;

        try
        {
            string initialPath = nativeFileBrowser0.Path;
            string newPath = nativeFileBrowser01.Path;

            if (string.IsNullOrEmpty(initialPath) ||
                string.IsNullOrEmpty(newPath))
            {
                theUI.NXMessageBox.Show(
                    "Spot Location Verification",
                    NXMessageBox.DialogType.Error,
                    "Please select both Initial and New spot data files.");
                return 1;
            }

            if (!File.Exists(initialPath) || !File.Exists(newPath))
            {
                theUI.NXMessageBox.Show(
                    "Spot Location Verification",
                    NXMessageBox.DialogType.Error,
                    "Selected file path is invalid.");
                return 1;
            }

            double tolerance = double0.Value;
            string comparisonMethod = enum0.ValueAsString;
            Dictionary<string, Spot> oldSpots = ReadExcel(initialPath);
            Dictionary<string, Spot> newSpots = ReadExcel(newPath);

            int shiftedCount = 0;
            int newCount = 0;
            int deletedCount = 0;

            // -------- Compare New vs Old --------
            foreach (var pair in newSpots)
            {
                if (oldSpots.ContainsKey(pair.Key))
                {
                    Spot oldS = oldSpots[pair.Key];
                    Spot newS = pair.Value;

                    double dx = Math.Abs(oldS.X - newS.X);
                    double dy = Math.Abs(oldS.Y - newS.Y);
                    double dz = Math.Abs(oldS.Z - newS.Z);
                    double dist = Distance(oldS, newS);

                    bool isShifted = (comparisonMethod == "Axis-wise")
                        ? (dx <= tolerance && dy <= tolerance && dz <= tolerance)
                        : (dist <= tolerance);

                    if (isShifted)
                        shiftedCount++;
                    else
                        newCount++;   // exceeds tolerance → NEW spot
                }
                else
                {
                    newCount++;       // spot not found in old → NEW
                }
            }

            // -------- Deleted Spots --------
            foreach (var pair in oldSpots)
            {
                if (!newSpots.ContainsKey(pair.Key))
                    deletedCount++;
            }

            // -------- Summary --------
            theUI.NXMessageBox.Show(
                "Spot Location Verification Result",
                NXMessageBox.DialogType.Information,
                $"Shifted Spots : {shiftedCount}\n" +
                $"New Spots     : {newCount}\n" +
                $"Deleted Spots : {deletedCount}");

        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString());
        }

        return errorCode;
    }
    private Dictionary<string, Spot> ReadExcel(string path)
    {
        Dictionary<string, Spot> spots = new Dictionary<string, Spot>();

        using (var package = new ExcelPackage(new FileInfo(path)))
        {
            ExcelWorksheet ws = package.Workbook.Worksheets.FirstOrDefault();
            if (ws == null)
                throw new Exception("Excel file has no worksheets.");

            int row = 2;

            while (true)
            {
                object idObj = ws.Cells[row, 1].Value;
                if (idObj == null || string.IsNullOrWhiteSpace(idObj.ToString()))
                    break;

                object xObj = ws.Cells[row, 2].Value;
                object yObj = ws.Cells[row, 3].Value;
                object zObj = ws.Cells[row, 4].Value;

                // stop if coordinates missing
                if (xObj == null || yObj == null || zObj == null)
                    break;

                if (!double.TryParse(xObj.ToString(), out double x) ||
                    !double.TryParse(yObj.ToString(), out double y) ||
                    !double.TryParse(zObj.ToString(), out double z))
                {
                    row++;
                    continue; // skip dirty rows
                }

                spots[idObj.ToString().Trim()] = new Spot
                {
                    Id = idObj.ToString().Trim(),
                    X = x,
                    Y = y,
                    Z = z
                };

                row++;
            }
        }
        return spots;
    }


    //private Dictionary<string, Spot> ReadExcel(string path)
    //{
    //    Dictionary<string, Spot> spots = new Dictionary<string, Spot>();

    //    using (ExcelPackage package = new ExcelPackage(new FileInfo(path)))
    //    {
    //        ExcelWorksheet ws = package.Workbook.Worksheets[0];
    //        int row = 2;

    //        while (!string.IsNullOrEmpty(ws.Cells[row, 1].Text))
    //        {
    //            Spot s = new Spot();
    //            s.Id = ws.Cells[row, 1].Text;
    //            s.X = Convert.ToDouble(ws.Cells[row, 2].Text);
    //            s.Y = Convert.ToDouble(ws.Cells[row, 3].Text);
    //            s.Z = Convert.ToDouble(ws.Cells[row, 4].Text);

    //            spots[s.Id] = s;
    //            row++;
    //        }
    //    }
    //    return spots;
    //}


    private double Distance(Spot a, Spot b)
    {
        return Math.Sqrt(
            Math.Pow(a.X - b.X, 2) +
            Math.Pow(a.Y - b.Y, 2) +
            Math.Pow(a.Z - b.Z, 2));
    }


    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if(block == nativeFileBrowser0)
            {
            //---------Enter your code here-----------
            }
            else if(block == nativeFileBrowser01)
            {
            //---------Enter your code here-----------
            }
            else if(block == double0)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum0)
            {
            //---------Enter your code here-----------
            }
            else if (block == reportButton)
            {
                apply_cb();
            }

        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    class Spot
    {
        public string Id;
        public double X;
        public double Y;
        public double Z;
    }


    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    
}
